//
//  ListOffreBenevolat.swift
//  ProjetAso
//
//  Created by Apprenant 06 on 06/02/2023.
//

import SwiftUI

struct OffreBenevolat: Identifiable {
    let id = UUID()
    var nameAssociation: String
    var titreMission: String
    var presentationAssociation: String
    var mission: String
    var imageOffre: String
    var disponibilite: String
    var logoAssociation: String
    var isliked: Bool = false
    
}

var offresBenevolat = [
    
    // Offres Restos du Coeur
    
    OffreBenevolat(nameAssociation: "Les Restos du Coeur", titreMission: "Chargé.e de mission Régional", presentationAssociation: "Fondés par Coluche en 1985, les Restos du Cœur ont pour but « d'aider et d'apporter une assistance bénévole aux personnes démunies, notamment dans le domaine alimentaire par l'accès à des repas gratuits, et par la participation à leur insertion sociale et économique ». Les restaurants du Cœur agissent entre autres dans l’aide alimentaire, l’aide aux gens de la rue, l’aide à l’emploi, l'accès aux droits et à la justice.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "RestosDuCoeur"),
    
    OffreBenevolat(nameAssociation: "Les Restos du Coeur", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "Fondés par Coluche en 1985, les Restos du Cœur ont pour but « d'aider et d'apporter une assistance bénévole aux personnes démunies, notamment dans le domaine alimentaire par l'accès à des repas gratuits, et par la participation à leur insertion sociale et économique ». Les restaurants du Cœur agissent entre autres dans l’aide alimentaire, l’aide aux gens de la rue, l’aide à l’emploi, l'accès aux droits et à la justice.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "RestosDuCoeur"),
    
    OffreBenevolat(nameAssociation: "Les Restos du Coeur", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "Fondés par Coluche en 1985, les Restos du Cœur ont pour but « d'aider et d'apporter une assistance bénévole aux personnes démunies, notamment dans le domaine alimentaire par l'accès à des repas gratuits, et par la participation à leur insertion sociale et économique ». Les restaurants du Cœur agissent entre autres dans l’aide alimentaire, l’aide aux gens de la rue, l’aide à l’emploi, l'accès aux droits et à la justice.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "RestosDuCoeur"),
    
    
    // Offres Secours Populaire

    
    OffreBenevolat(nameAssociation: "Le Secours Populaire", titreMission: "Chargé.e de mission Régional", presentationAssociation: "Le Secours populaire français, est une association française de solidarité à but non lucratif, qui intervient sur le plan matériel, médical, moral et juridique, auprès des personnes victimes de l’injustice sociale, des calamités naturelles, de la misère, de la faim, du sous-développement, des conflits armés.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre4", disponibilite: "1 jour par semaine", logoAssociation: "SecoursPopulaire"),
    
    OffreBenevolat(nameAssociation: "Le Secours Populaire", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "Le Secours populaire français, est une association française de solidarité à but non lucratif, qui intervient sur le plan matériel, médical, moral et juridique, auprès des personnes victimes de l’injustice sociale, des calamités naturelles, de la misère, de la faim, du sous-développement, des conflits armés.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre5", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "SecoursPopulaire"),
    
    OffreBenevolat(nameAssociation: "Le Secours Populaire", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "Le Secours populaire français, est une association française de solidarité à but non lucratif, qui intervient sur le plan matériel, médical, moral et juridique, auprès des personnes victimes de l’injustice sociale, des calamités naturelles, de la misère, de la faim, du sous-développement, des conflits armés.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre6", disponibilite: "1 jour par semaine", logoAssociation: "SecoursPopulaire"),
    
    
    // Offres Banque Alimentaire

    
    
    OffreBenevolat(nameAssociation: "La Banque Alimentaire", titreMission: "Chargé.e de mission Régional", presentationAssociation: "Créée en 1986, la Banque Alimentaire de Toulouse et sa région fournit en denrées alimentaires et produits d’hygiène plus de 100 associations partenaires qui viennent en aide à plus de 20 000 bénéficiaires chaque semaine sur Toulouse, la Haute-Garonne, L’Ariège et le Tarn-et-Garonne. Elle fournit 2 700 tonnes de produits par an grâce à ses 100 bénévoles, ses 38 salariés dont 33 en contrat d’insertion et ses jeunes volontaires en service civique (en 2020).", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "BanqueAlimentaire"),
    
    OffreBenevolat(nameAssociation: "La Banque Alimentaire", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "Créée en 1986, la Banque Alimentaire de Toulouse et sa région fournit en denrées alimentaires et produits d’hygiène plus de 100 associations partenaires qui viennent en aide à plus de 20 000 bénéficiaires chaque semaine sur Toulouse, la Haute-Garonne, L’Ariège et le Tarn-et-Garonne. Elle fournit 2 700 tonnes de produits par an grâce à ses 100 bénévoles, ses 38 salariés dont 33 en contrat d’insertion et ses jeunes volontaires en service civique (en 2020).", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "BanqueAlimentaire"),
    
    OffreBenevolat(nameAssociation: "La Banque Alimentaire", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "Créée en 1986, la Banque Alimentaire de Toulouse et sa région fournit en denrées alimentaires et produits d’hygiène plus de 100 associations partenaires qui viennent en aide à plus de 20 000 bénéficiaires chaque semaine sur Toulouse, la Haute-Garonne, L’Ariège et le Tarn-et-Garonne. Elle fournit 2 700 tonnes de produits par an grâce à ses 100 bénévoles, ses 38 salariés dont 33 en contrat d’insertion et ses jeunes volontaires en service civique (en 2020).", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "BanqueAlimentaire"),
    
    
    // Offres La Croix Rouge Française

    
    
    OffreBenevolat(nameAssociation: "La Croix Rouge Française", titreMission: "Chargé.e de mission Régional", presentationAssociation: "La Croix-Rouge française est une association de bénévoles et également une entreprise à but non lucratif de services humanitaire, sanitaire et médicosocial. L’association compte chaque jour sur son réseau de bénévoles et de salariés pour agir en privilégiant les actions de proximité en apportant des réponses concrètes et durables. Les bénévoles agissent pour prévenir et alléger les souffrances humaines.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "BanqueAlimentaire"),
    
    OffreBenevolat(nameAssociation: "La Croix Rouge Française", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "La Croix-Rouge française est une association de bénévoles et également une entreprise à but non lucratif de services humanitaire, sanitaire et médicosocial. L’association compte chaque jour sur son réseau de bénévoles et de salariés pour agir en privilégiant les actions de proximité en apportant des réponses concrètes et durables. Les bénévoles agissent pour prévenir et alléger les souffrances humaines.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "BanqueAlimentaire"),
    
    OffreBenevolat(nameAssociation: "La Croix Rouge Française", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "La Croix-Rouge française est une association de bénévoles et également une entreprise à but non lucratif de services humanitaire, sanitaire et médicosocial. L’association compte chaque jour sur son réseau de bénévoles et de salariés pour agir en privilégiant les actions de proximité en apportant des réponses concrètes et durables. Les bénévoles agissent pour prévenir et alléger les souffrances humaines.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "BanqueAlimentaire"),
    
    
    
    // Offres Le Secours Catholique

    
    OffreBenevolat(nameAssociation: "Le Secours Catholique", titreMission: "Chargé.e de mission Régional", presentationAssociation: "Le Secours Catholique a pour objectif de s'associer avec les personnes en difficulté pour ensemble chercher les moyens de résoudre leurs difficultés et mettre en valeur leurs ressources individuellement et collectivement.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "SecoursCatholique"),
    
    OffreBenevolat(nameAssociation: "Le Secours Catholique", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "Le Secours Catholique a pour objectif de s'associer avec les personnes en difficulté pour ensemble chercher les moyens de résoudre leurs difficultés et mettre en valeur leurs ressources individuellement et collectivement.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "SecoursCatholique"),
    
    OffreBenevolat(nameAssociation: "Le Secours Catholique", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "Le Secours Catholique a pour objectif de s'associer avec les personnes en difficulté pour ensemble chercher les moyens de résoudre leurs difficultés et mettre en valeur leurs ressources individuellement et collectivement.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "SecoursCatholique"),
    
    
    // Offres La Main à la Pate

    
    OffreBenevolat(nameAssociation: "La Main à la Pate", titreMission: "Chargé.e de mission Régional", presentationAssociation: "La Main à la Pâte est une épicerie solidaire située à Toulouse. L'objectif étant d'apporter une aide alimentaire à un public précaire. L'épicerie solidaire est également un support, un espace convivial mais aussi un lieu de conseil et d'écoute pour accompagner les bénéficiaires dans l'élaboration de leur projet personnel.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "LaMainALaPate"),
    
    OffreBenevolat(nameAssociation: "La Main à la Pate", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "La Main à la Pâte est une épicerie solidaire située à Toulouse. L'objectif étant d'apporter une aide alimentaire à un public précaire. L'épicerie solidaire est également un support, un espace convivial mais aussi un lieu de conseil et d'écoute pour accompagner les bénéficiaires dans l'élaboration de leur projet personnel.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "LaMainALaPate"),
    
    OffreBenevolat(nameAssociation: "La Main à la Pate", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "La Main à la Pâte est une épicerie solidaire située à Toulouse. L'objectif étant d'apporter une aide alimentaire à un public précaire. L'épicerie solidaire est également un support, un espace convivial mais aussi un lieu de conseil et d'écoute pour accompagner les bénéficiaires dans l'élaboration de leur projet personnel.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "LaMainALaPate"),
    
    
    // Offres Saint-Vincent-de-Paul

    
    OffreBenevolat(nameAssociation: "Saint-Vincent-de-Paul", titreMission: "Chargé.e de mission Régional", presentationAssociation: "La Société de Saint-Vincent-de-Paul est une association d’utilité publique dont les bénévoles tendent quotidiennement la main aux plus vulnérables. Dans toute la France, elle constitue un dense réseau associatif de solidarité qui lutte aussi bien contre la solitude que contre la pauvreté.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "SaintVincentDePaul"),
    
    OffreBenevolat(nameAssociation: "Saint-Vincent-de-Paul", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "La Société de Saint-Vincent-de-Paul est une association d’utilité publique dont les bénévoles tendent quotidiennement la main aux plus vulnérables. Dans toute la France, elle constitue un dense réseau associatif de solidarité qui lutte aussi bien contre la solitude que contre la pauvreté.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "SaintVincentDePaul"),
    
    OffreBenevolat(nameAssociation: "Saint-Vincent-de-Paul", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "La Société de Saint-Vincent-de-Paul est une association d’utilité publique dont les bénévoles tendent quotidiennement la main aux plus vulnérables. Dans toute la France, elle constitue un dense réseau associatif de solidarité qui lutte aussi bien contre la solitude que contre la pauvreté.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "SaintVincentDePaul"),
    
    
    // Offres ARCEA

    
    OffreBenevolat(nameAssociation: "Arcea", titreMission: "Chargé.e de mission Régional", presentationAssociation: "L'Association ARCEA met à disposition : des ressources, des compétences, des conseils en vue de redonner confiance et espoir aux personnes accueillies. Nous souhaitons être un lieu d’écoute, de lien social, dans un cadre convivial et ouvert, où différentes expériences de vie se côtoient. ARCEA est une association loi 1901 à but non lucratif, créée en Septembre 2012 elle s’appuie sur plus de 10 ans d’expérience dans l’aide alimentaire, portée par une association mère, elle poursuit son développement pour tenter de répondre en partie aux besoins des foyers en difficulté.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "Arcea"),
    
    OffreBenevolat(nameAssociation: "Arcea", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "L'Association ARCEA met à disposition : des ressources, des compétences, des conseils en vue de redonner confiance et espoir aux personnes accueillies. Nous souhaitons être un lieu d’écoute, de lien social, dans un cadre convivial et ouvert, où différentes expériences de vie se côtoient. ARCEA est une association loi 1901 à but non lucratif, créée en Septembre 2012 elle s’appuie sur plus de 10 ans d’expérience dans l’aide alimentaire, portée par une association mère, elle poursuit son développement pour tenter de répondre en partie aux besoins des foyers en difficulté.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "Arcea"),
    
    OffreBenevolat(nameAssociation: "Arcea", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "L'Association ARCEA met à disposition : des ressources, des compétences, des conseils en vue de redonner confiance et espoir aux personnes accueillies. Nous souhaitons être un lieu d’écoute, de lien social, dans un cadre convivial et ouvert, où différentes expériences de vie se côtoient. ARCEA est une association loi 1901 à but non lucratif, créée en Septembre 2012 elle s’appuie sur plus de 10 ans d’expérience dans l’aide alimentaire, portée par une association mère, elle poursuit son développement pour tenter de répondre en partie aux besoins des foyers en difficulté.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "Arcea"),
    
    
    // Offres Médecins du Monde

    
    OffreBenevolat(nameAssociation: "Médecins du Monde", titreMission: "Chargé.e de mission Régional", presentationAssociation: "Médecins du monde est une ONG médicale de solidarité internationale créée en 1980. Elle intervient en France et à l'étranger, afin de soigner les populations les plus vulnérables, les victimes de conflits armés, de catastrophes naturelles, celles et ceux qui n’ont pas accès aux soins.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "MedecinDuMonde"),
    
    OffreBenevolat(nameAssociation: "Médecins du Monde", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "Médecins du monde est une ONG médicale de solidarité internationale créée en 1980. Elle intervient en France et à l'étranger, afin de soigner les populations les plus vulnérables, les victimes de conflits armés, de catastrophes naturelles, celles et ceux qui n’ont pas accès aux soins.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "MedecinDuMonde"),
    
    OffreBenevolat(nameAssociation: "Médecins du Monde", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "Médecins du monde est une ONG médicale de solidarité internationale créée en 1980. Elle intervient en France et à l'étranger, afin de soigner les populations les plus vulnérables, les victimes de conflits armés, de catastrophes naturelles, celles et ceux qui n’ont pas accès aux soins.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "MedecinDuMonde"),
    
    
    // Offres Emmaüs

    
    OffreBenevolat(nameAssociation: "Emmaüs Toulouse", titreMission: "Chargé.e de mission Régional", presentationAssociation: "L’association Emmaüs a pour objectifs : l’accompagnement, l’insertion, et l’autonomie des plus démunis. Agissant dans un esprit de solidarité et d’entraide, elle propose notamment des actions visant à soutenir les droits et la dignité des plus démunis, des lieux d’accueil, d’hébergement et d’aide alimentaire ainsi que des services d’accompagnement et d’insertion par l’activité économique et l’accès au logement.", mission: "Accompagner le Responsable Départemental dans la mise en application de son projet associatif (Activités, projets, financements) et par ce biais aider au développement de l’activité opérationnelle. Participer aux réunions statutaires (Bureaux, CA) ainsi qu’aux réunions de l’équipe de la Délégation Régionale pour partager les informations et mutualiser les bonnes pratiques. Veiller au bon fonctionnement de l’Association Départementale et en particulier de la bonne gestion des Ressources Humaines (bénévoles et salariés). Le Chargé de mission s’engage dans une équipe nationale et régionale. C’est un rôle de support au département sur les différents projets et de facilitateur dans l’élaboration et la mise en œuvre terrain. C’est une fonction de réflexion et d’actions en étroite collaboration avec les équipes en place.", imageOffre: "imageOffre1", disponibilite: "1 jour par semaine", logoAssociation: "EmmausToulouse"),
    
    OffreBenevolat(nameAssociation: "Emmaüs Toulouse", titreMission: "Participe à la Collecte Nationale alimentaire 2023", presentationAssociation: "L’association Emmaüs a pour objectifs : l’accompagnement, l’insertion, et l’autonomie des plus démunis. Agissant dans un esprit de solidarité et d’entraide, elle propose notamment des actions visant à soutenir les droits et la dignité des plus démunis, des lieux d’accueil, d’hébergement et d’aide alimentaire ainsi que des services d’accompagnement et d’insertion par l’activité économique et l’accès au logement.", mission: "Participe à la Collecte Nationale alimentaire pour nous aider à atteindre notre objectif 2023 de dépasser les 9 000 tonnes, soit l'équivalent de 9 millions de repas supplémentaires pour les plus démuni·es ! Rejoins-nous le 3, 4 et/ou le 5 mars prochain dans toute la France pour cette action de bénévolat et fais vivre la solidarité dans un esprit de partage et de bonne humeur !", imageOffre: "imageOffre2", disponibilite: "Disponible un peu : Accueille le public à l’entrée des magasins, réceptionne les denrées données par les clients et trie les produits pour leur mise en carton, quelques heures ou le temps d'une journée. Disponible beaucoup : Prends en charge de A à Z un magasin sur l’ensemble du week-end ou sur une journée complète en constituant ton équipe et le planning.", logoAssociation: "EmmausToulouse"),
    
    OffreBenevolat(nameAssociation: "Emmaüs Toulouse", titreMission: "Référent.e ressource bénévole pour une association d'aide aux démunis", presentationAssociation: "L’association Emmaüs a pour objectifs : l’accompagnement, l’insertion, et l’autonomie des plus démunis. Agissant dans un esprit de solidarité et d’entraide, elle propose notamment des actions visant à soutenir les droits et la dignité des plus démunis, des lieux d’accueil, d’hébergement et d’aide alimentaire ainsi que des services d’accompagnement et d’insertion par l’activité économique et l’accès au logement.", mission: "Homme ou femme, tu sais motiver, soutenir, encourager ? Tu es autonome, attentif aux autres et très organisé ? Tu as pratiqué l’animation d’équipe ou tu te sens capable de le faire ? Deviens référent des ressources bénévoles. Pas besoin d’être un spécialiste des RH, mais sens de l’écoute et du dialogue indispensable ! Réaliser un état des lieux permanent des besoins en bénévoles. Rechercher des candidats. Accueillir et accompagner les nouvelles bonnes volontés indispensables au bon fonctionnement de notre association départementale de la Haute-Garonne : bénévoles mais aussi stagiaires, services civiques, etc. Gérer les candidatures avec un logiciel interne que tu devras tenir à jour. Suivre l'intégrations des nouveaux bénévoles puis leur parcours. Animer le réseau de Relais Ressources Bénévoles de l'ensemble des structures Restos du département.", imageOffre: "imageOffre3", disponibilite: "1 jour par semaine", logoAssociation: "EmmausToulouse")
]



